force_ltr no
font_size 13
enable_audio_bell no
cursor_shape block
cursor_beam_thickness 20

font_family JetBrainsMonoNerdFont-Bold

background_tint      0.2
background_opacity   0.7
background            #000000
foreground            #adadad
cursor                #adadad
selection_background  #C8C093
color0                #000000
color8                #545454
color1                #fa5355
color9                #fb7172
color10               #67ff4f
color3                #c2c300
color11               #ffff00
color4                #4581eb
color12               #6d9df1
color5                #fa54ff
color13               #fb82ff
color6                #33c2c1
color14               #60d3d1
color7                #adadad
color15               #eeeeee
