[window]
dynamic_padding = true
opacity = 0.85
dynamic_title = true

[font]
size = 15
normal = {family = "JetBrainsMonoNL Nerd Font", style = "Regular"}
bold = {family = "JetBrainsMonoNL Nerd Font", style = "Bold"}
italic = {family = "JetBrainsMonoNL Nerd Font", style = "italic"}
bold_italic = {family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic"}

[general]
import = [
	"~/.config/alacritty/kanagaw_dragon.toml"
]
